### ISSUE TITLE
Error in reactable: `columns` names must exist in `data`

### ISSUE THREAD

**Issue by jennybc** [gadenbuie/branchMover#5]
I'm seeing `` Error in reactable: `columns` names must exist in `data` `` when I run the app.

It looks like the problem is that the columns `issue`, `state`, `created_at`, and `issue_url` don't (necessarily?) exist in `repos_df`:

https://github.com/gadenbuie/branchMover/blob/c7f1a163a9576cd819f53bf1459fafc6c2c40fda/R/repos_reactable.R#L65-L75

**Comment by gadenbuie** [comment]
Yikes! Thanks for testing and reporting, this should be fixed now
